In [1]:
import numpy as np
import pandas as pd

In [2]:
data1=pd.read_csv(r'/kaggle/input/diabetes-type-prediction/pima-indians-diabetes.csv')
data1.head()

Preg  Plas  Pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [3]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Preg    768 non-null    int64  
 1   Plas    768 non-null    int64  
 2   Pres    768 non-null    int64  
 3   skin    768 non-null    int64  
 4   test    768 non-null    int64  
 5   mass    768 non-null    float64
 6   pedi    768 non-null    float64
 7   age     768 non-null    int64  
 8   class   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [4]:
data1.describe()

Preg        Plas        Pres        skin        test        mass  \
count  768.000000  768.000000  768.000000  768.000000  768.000000  768.000000   
mean     3.845052  120.894531   69.105469   20.536458   79.799479   31.992578   
std      3.369578   31.972618   19.355807   15.952218  115.244002    7.884160   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000   99.000000   62.000000    0.000000    0.000000   27.300000   
50%      3.000000  117.000000   72.000000   23.000000   30.500000   32.000000   
75%      6.000000  140.250000   80.000000   32.000000  127.250000   36.600000   
max     17.000000  199.000000  122.000000   99.000000  846.000000   67.100000   

             pedi         age       class  
count  768.000000  768.000000  768.000000  
mean     0.471876   33.240885    0.348958  
std      0.331329   11.760232    0.476951  
min      0.078000   21.000000    0.000000  
25%      0.243750   24.000000    0.000000  
50%      0.372500   29.000000    0.000000  
75%      0.626250   41.000000    1.000000  
max      2.420000   81.000000    1.000000

In [5]:
y=data1['class']
x=data1.drop('class', axis=1)

In [6]:
x.head()

Preg  Plas  Pres  skin  test  mass   pedi  age
0     6   148    72    35     0  33.6  0.627   50
1     1    85    66    29     0  26.6  0.351   31
2     8   183    64     0     0  23.3  0.672   32
3     1    89    66    23    94  28.1  0.167   21
4     0   137    40    35   168  43.1  2.288   33

In [7]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: class, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=42)

In [10]:
x_train.shape, x_test.shape

((614, 8), (154, 8))

In [11]:
y_train.shape, y_test.shape

((614,), (154,))

In [12]:
from sklearn.tree import DecisionTreeClassifier

In [13]:
dt_model= DecisionTreeClassifier()
dt_model

DecisionTreeClassifier()

In [14]:
dt_model.fit(x_train,y_train)

DecisionTreeClassifier()

In [15]:
y_pred=dt_model.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0])

In [16]:
from sklearn.metrics import accuracy_score, classification_report

In [17]:
accuracy=accuracy_score(y_test,y_pred)
accuracy

0.7792207792207793

In [18]:
report=classification_report(y_test,y_pred)

In [19]:
print(report)

              precision    recall  f1-score   support

           0       0.85      0.80      0.82        99
           1       0.67      0.75      0.71        55

    accuracy                           0.78       154
   macro avg       0.76      0.77      0.76       154
weighted avg       0.79      0.78      0.78       154



# THUS, MODELS ACCURACY IS 75%. 

# Now, lets Build a RANDOM FOREST MODEL AND TRY TO INCREASE THE MODELS ACCURACY

In [20]:
from sklearn.ensemble import RandomForestClassifier

In [21]:
rf_model= RandomForestClassifier(random_state=42)
rf_model

RandomForestClassifier(random_state=42)

In [22]:
rf_model.fit(x_train,y_train)

RandomForestClassifier(random_state=42)

In [23]:
y_pred_rf=rf_model.predict(x_test)
y_pred_rf

array([0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [24]:
accuracy_score(y_test,y_pred)

0.7792207792207793

# Thus, accuracy using random forest model is also ~75%. 

# Q is how to increase accuracy of a decision tree model or a randomforest model?

# 1. use GRIDSEARCHCV TO FIND THE OPTIMUM HYPER PARAMETERS or manually change the hyper parameters and check its accuracy to arrive at the optimum hyper parameters

# 2. do the DATA PREPROCESSING more properly like normalize the inputs before training the model

# 3. HYPER PARAMETER TUNING

# 4. USE ENSEMBLE METHODS i.e TKAE MULTIPLE DECISION TREES RESPONSES example random forest model . can also use BAGGING AND BOOSTING ?

# 5. Do CROSS VALIDATION to recheck whether your model is overfitting the responses or not? 

# 6. do PRUNING i.e remove branches that have little importance?

# 7. VISUALIZE FEATURE IMPORTANCE ?

# LETS NORMALIZE THE DATA USING ZSCORE AND THEN APPLY DECISION TREE AND RANDOM FOREST MODELS

In [25]:
from scipy.stats import zscore

In [26]:
data2=pd.read_csv(r'/kaggle/input/diabetes-type-prediction/pima-indians-diabetes.csv')
data2.head()

Preg  Plas  Pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [27]:
y=data2['class']
x=data2.drop('class',axis=1)

In [28]:
x=x.apply(zscore)

In [29]:
x.head()

Preg      Plas      Pres      skin      test      mass      pedi  \
0  0.639947  0.848324  0.149641  0.907270 -0.692891  0.204013  0.468492   
1 -0.844885 -1.123396 -0.160546  0.530902 -0.692891 -0.684422 -0.365061   
2  1.233880  1.943724 -0.263941 -1.288212 -0.692891 -1.103255  0.604397   
3 -0.844885 -0.998208 -0.160546  0.154533  0.123302 -0.494043 -0.920763   
4 -1.141852  0.504055 -1.504687  0.907270  0.765836  1.409746  5.484909   

        age  
0  1.425995  
1 -0.190672  
2 -0.105584  
3 -1.041549  
4 -0.020496

In [30]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: class, dtype: int64

In [31]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42)

In [32]:
x_train.shape, x_test.shape

((614, 8), (154, 8))

In [33]:
dt_model2=DecisionTreeClassifier(random_state=42)
dt_model2

DecisionTreeClassifier(random_state=42)

In [34]:
dt_model2.fit(x_train, y_train)

DecisionTreeClassifier(random_state=42)

In [35]:
y_pred3=dt_model2.predict(x_test)
y_pred3

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0])

In [36]:
accuracy_score(y_test,y_pred3)

0.7467532467532467

# ACCURACY HAS STILL NOT IMPROVED(EVEN WITH NORMALIZATION)

# NOW, LETS USE RANDOMFOREST MODEL WITH THE NORMALIZED DATA

In [37]:
rf_model2=RandomForestClassifier(random_state=42)
rf_model2

RandomForestClassifier(random_state=42)

In [38]:
rf_model2.fit(x_train,y_train)

RandomForestClassifier(random_state=42)

In [39]:
y_pred4=rf_model2.predict(x_test)
y_pred4

array([0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [40]:
accuracy_score(y_test,y_pred4)

0.7272727272727273

#  Now, lets do HYPER PARAMETERS TUNING and then see the models accuracy

In [41]:
dt_model3=DecisionTreeClassifier(criterion='gini',
                                 max_depth=5,
                                 #min_samples_leaf=,15
                                 min_samples_split=15,)

dt_model3

DecisionTreeClassifier(max_depth=5, min_samples_split=15)

In [42]:
dt_model3.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=5, min_samples_split=15)

In [43]:
y_pred5=dt_model3.predict(x_test)
y_pred5

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [44]:
accuracy_score(y_test,y_pred5)

0.7922077922077922

# Thus, ACCURACY HAS INCREASED BY ~5% after doing NORMALIZATION AND HYPER PARAMETERS TUNING